### ISSUE TITLE
Conflict with snippets

### ISSUE THREAD

**Issue by mickleberry** [jameskoster/woocommerce-product-archive-customiser#14]
ah, something bad bad bad happened. This plugin was working fine before. 

I had it turned off though.. then patched in a snippet from here: https://support.woothemes.com/hc/en-us/articles/203106047-Customize-the-Sorting-Dropdown ..and when i turned your plugin back on it broke the whole gallery (divide by zero). 

Then when i turned off the plugin, the snippet was broken too. Urgh, whoops. 

Does your plugin make changes that stay in place after deactivating?

**Comment by jameskoster** [comment]
Nope, once it's been deactivated nothing will stay in place. That filter should be unrelated. I wonder if the conflict is coming from the theme instead?
