### ISSUE TITLE
Price and thumbnail dissapear when activating this

### ISSUE THREAD

**Issue by ukscotth** [jameskoster/woocommerce-product-archive-customiser#17]
Hi,

When I activate this plugin my product thumbnails and price dissapear, any ideas ?

Thanks,

Scott

**Comment by ukscotth** [comment]
Ive just noticed it works fine in customiser view but when i exit customiser it doesnt :(

**Comment by jameskoster** [comment]
Try re-saving the options in the Customizer.

**Comment by ukscotth** [comment]
Thanks. That worked +1:
