### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by ben72** [jameskoster/woocommerce-product-archive-customiser#19]
Does not seem to work with the latest version of Woocommerce?

Warning: Division by zero in /home/xxx/public_html/yyy/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 250

Warning: Division by zero in /home/xxx/public_html/yyy/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 252

**Comment by jameskoster** [comment]
Have you updated from an older version? Try re-setting the column setting in the Customizer and re-saving.

**Comment by BFTrick** [comment]
I just created a new site and I'm not seeing this issue. Might have something to do with an update?

**Comment by jameskoster** [comment]
Pretty sure that's the case. Gonna close this out for now, re-open if you notice it continuously @ben72
