### ISSUE TITLE
Product Columns Don't Work

### ISSUE THREAD

**Issue by BFTrick** [jameskoster/woocommerce-product-archive-customiser#20]
The columns aren't working. I suspect the math is off by a bit? 

If I select 2, 3, 4, or 5 it usually shows 1 less than that. And the next row shows just 1 product. Basically not working. :(

Screenshot: 
<img width="849" alt="products_ _woocommerce" src="https://cloud.githubusercontent.com/assets/1065372/19125001/a1241f92-8af2-11e6-966f-f357b1237ba6.png">

Full screencast: http://d.pr/i/4fVS

**Comment by jameskoster** [comment]
Pretty sure this is a Storefront specific issue, will look into making the plugin css a bit stricter.

**Comment by glumb** [comment]
Any update regarding this issue? Im using storefront, too.
