### ISSUE TITLE
Display Product Sorting Option Doesn't Work on Storefront

### ISSUE THREAD

**Issue by BFTrick** [jameskoster/woocommerce-product-archive-customiser#22]
The `display product sorting` checkbox doesn't work on Storefront.

Screencast: http://d.pr/i/Jcix

## Problem

That's because the plugin removes `woocommerce_catalog_ordering` at a specific priority and Storefront has already removed that priority and added it back in at another priority.

Here's what the plugin does:

``` php
// Product Ordering.
if ( get_theme_mod( 'wc_pac_product_sorting', true ) === false ) {
	remove_action( 'woocommerce_before_shop_loop', 'woocommerce_catalog_ordering', 30 );
}
```

Here's what Storefront is doing (adding some ellipses for brevity):

``` php
remove_action( 'woocommerce_before_shop_loop', 'woocommerce_catalog_ordering', 30 );

...

add_action( 'woocommerce_after_shop_loop', 'woocommerce_catalog_ordering', 10 );

...

add_action( 'woocommerce_before_shop_loop', 'woocommerce_catalog_ordering', 10 );
```

## Possible Solution

Now there is an underlying issue in the WordPress world trying to modify something that another plugin/theme has already modified. And doing a big overhaul would have backwards compatibility issues.

But I think in this specific case since the user doesn't want it at all. We could add another two lines to the Product Archive Customiser so it does something like this:

``` php
// Product Ordering.
if ( get_theme_mod( 'wc_pac_product_sorting', true ) === false ) {
	remove_action( 'woocommerce_before_shop_loop', 'woocommerce_catalog_ordering', 30 );

	// For Storefront themes
	remove_action( 'woocommerce_after_shop_loop', 'woocommerce_catalog_ordering', 10 );
	remove_action( 'woocommerce_before_shop_loop', 'woocommerce_catalog_ordering', 10 );
}
```

If you think this is the best way forward let me know and I can send a PR. :)

**Comment by jameskoster** [comment]
I wonder if there's a way we can catch all themes?

Kinda hacky, but we could add a body class and then add a `display: none;` rule as a fallback. So for themes using the default priority the element is removed entirely (as it is now). And for those than don't, it will at least still be hidden. Obviously this isn't ideal, but it would make the option work 99.9%.

What do you think?

**Comment by BFTrick** [comment]
Oooooh. I like your way better. 

Shall I send a PR?

**Comment by jameskoster** [comment]
Yes please! :)
