### ISSUE TITLE
Storefront: Changing displayed columns on mobile view

### ISSUE THREAD

**Issue by chrizjr** [jameskoster/woocommerce-product-archive-customiser#25]
Hi!

Thanks a lot for developing this great tool! It helps me as a NGO non-IT staff A LOT!

Currently I am using the storefront theme which is responsive to mobile devices. The plugin works brilliantly for the desktop view but couldn't change the mobile view. The storefront theme default showing only 1 column for mobile view but I would like to change to 3 columns. Is there any way to change that?

Thanks again for your help!

**Comment by jameskoster** [comment]
This would involve a pretty big plugin update to add the new feature. Unfortunately I don't really have time to work on it at the moment.

**Comment by chrizjr** [comment]
Anyway, thanks for your swift reply! :) Will try out other methods.
