### ISSUE TITLE
The number of columns doesn't work at all

### ISSUE THREAD

**Issue by bagusflyer** [jameskoster/woocommerce-product-archive-customiser#8]
Here is the setting for the columns:

![2014-10-29 8 44 33](https://cloud.githubusercontent.com/assets/1187737/4825813/659c3038-5f69-11e4-8785-313c53605fcd.png)

But the result is:

![2014-10-29 8 45 25](https://cloud.githubusercontent.com/assets/1187737/4825823/7c8100bc-5f69-11e4-873a-75d190c3f676.png)

Any idea? Thanks

**Comment by BFTrick** [comment]
I tested this in other themes and it worked fine. Probably a theme conflict of some sort. Maybe should close this due to inactivity?

**Comment by jameskoster** [comment]
Yeah if a theme is also tweaking the product columns filter then there's likely to be conflicts.
