### ISSUE TITLE
Is is possible to move things around with remove/add actions?

### ISSUE THREAD

**Issue by lmartins** [jameskoster/woocommerce-product-archive-customiser#9]
I was looking into the source code hoping to be able to move things around, for example by changing the place where the "per page" selector is displayed by removing the default action and assign it to a different hook?

Is this possible?

**Comment by jameskoster** [comment]
It's not really possible to re-arrange specific settings. You can see where they're hooked in here: https://github.com/jameskoster/woocommerce-product-archive-customiser/blob/master/archive-customiser.php#L160 So you can change where all the settings appear, if you want to.

**Comment by lmartins** [comment]
Hum, I should have been clearer in my question. I was not referring to the backend interface, I was referring to the per page selected displayed in the frontend where user can choose how many products per page he/she wishes to see.

**Comment by jameskoster** [comment]
Ah right. That should be possible. It's hooked in here: https://github.com/jameskoster/woocommerce-product-archive-customiser/blob/master/archive-customiser.php#L212 You could probably use css to move it as well.

**Comment by lmartins** [comment]
Ah cool. In this case I can't just rely on CSS because I need to move it around some markup.
I'll have to investigate how can I remove and add it back these hooks since they are declared within the class context, but at least im on the right track now. Thanks.

**Comment by lmartins** [comment]
From the docs I believe this should work:
```
if ( class_exists( 'WC_pac' ) ) {
    global $WC_pac;
    remove_action( 'woocommerce_before_shop_loop', array( $WC_pac, 'woocommerce_pac_show_product_perpage' ), 30 );
}
```
But it isn't producing any effect.
Is because of this note from the codex?
```
It is also worth noting that you may need to prioritise the removal of the action to a hook that occurs after the action is added. You cannot successfully remove the action before it has been added.
```
